<?php
declare(strict_types=1);
// Inherits the CLI, *_test database and explicit reset safeguards.
require __DIR__ . '/integration.php';
use App\{DB, SettingsService, CreditLedgerService, PDFService, DocumentData, Auth};

$settings = SettingsService::settings();
$settings['shipping_gst_rate'] = '18';
$settings['round_to_rupee'] = false;
$settings['payments'][] = 'Other';
SettingsService::save($settings, $admin);
$shipping = $input;
$shipping['shipping_charges'] = '100';
$shipping['items'] = [['product_name'=>'Goods','quantity'=>'1','rate'=>'1000','discount_mode'=>'Percent','discount_value'=>'10','gst_rate'=>'18','hsn_sac'=>'9983','unit'=>'pcs']];
$shipping['delivery_note'] = 'DN-123';
$shipping['buyer_order_number'] = 'PO-456';
$shipping['destination'] = 'Bengaluru';
$shipping['shipping_name'] = 'Consignee';
$shipping['billing_address'] = 'Test address';
$shipping['payment_allocations'] = [['method'=>'Cash','amount'=>'500','reference'=>'cash'],['method'=>'Other','amount'=>'680','reference'=>'test voucher']];
$invoice = $service->save($shipping, $owner);
check($invoice['shipping_gst']==='18.00' && $invoice['grand_total']==='1180.00' && $invoice['cgst']==='90.00' && $invoice['sgst']==='90.00', 'shipping included once in intra-state tax and total');
check($invoice['payment_status']==='Paid' && $invoice['amount_paid']==='1180.00' && count($invoice['payment_allocations'])===2, 'split full payment including Other saved');
check($invoice['delivery_note']==='DN-123' && $invoice['buyer_order_number']==='PO-456' && $invoice['shipping_name']==='Consignee', 'expanded fields round-trip');
$html = (new PDFService())->invoiceHtml($invoice);
check(str_contains($html,'Karnataka') && str_contains($html,'Of which shipping GST (18.00%)') && str_contains($html,'Shipping</td>'), 'invoice shows state name and separate shipping tax');
file_put_contents(ROOT.'/tmp/v2-invoice.pdf',(new PDFService())->render($html));
$hsn = $report->report($range + ['type'=>'hsn'])['rows'];
$shippingRow = array_values(array_filter($hsn,fn($r)=>$r['label']==='Shipping'))[0];
check($shippingRow['taxable']==='100.00' && $shippingRow['gst']==='18.00', 'HSN report includes shipping taxable and GST');
$settings['shipping_gst_rate']='5';
SettingsService::save($settings,$admin);
$edited = $service->save($invoice,$owner,(int)$invoice['id']);
check($edited['shipping_gst_rate']==='18.00' && $edited['grand_total']==='1180.00', 'editing preserves saved shipping tax after settings change');
$inter = $shipping;
$inter['place_of_supply']='27';
$inter['shipping_gst_rate']='18';
$inter['payment_allocations']=[];
$inter = $service->save($inter,$owner);
check($inter['igst']==='180.00' && $inter['cgst']==='0.00' && $inter['sgst']==='0.00', 'interstate shipping uses IGST');
file_put_contents(ROOT.'/tmp/v2-interstate.pdf',(new PDFService())->render((new PDFService())->invoiceHtml($inter)));
$bad = $shipping; $bad['shipping_charges']='-1';
rejects(fn()=>$service->save($bad,$owner),'negative shipping rejected');
$bad = $shipping; $bad['shipping_gst_rate']='101';
rejects(fn()=>$service->save($bad,$owner),'invalid shipping rate rejected');
$bad = $shipping; $bad['payment_allocations'][0]['amount']='9999';
rejects(fn()=>$service->save($bad,$owner),'overpayment rejected');
$due = $shipping;
$due['customer_mobile']='9000000001';
$due['shipping_gst_rate']='18';
$due['credit_bill']=true;
$due['payment_allocations']=[['method'=>'Cash','amount'=>'180']];
$bad=$due; $bad['billing_address']='';
rejects(fn()=>$service->save($bad,$owner),'credit bill requires address');
$credit = $service->save($due,$owner);
check($credit['amount_due']==='1000.00' && $credit['payment_status']==='Partially Paid','partial payment creates due');
$account=DB::one('SELECT * FROM credit_accounts WHERE customer_mobile=?',['9000000001']);
check($account['balance']==='1000.00','credit account matches invoice due');
$ledger=new CreditLedgerService();
$clear=['credit_account_id'=>$account['id'],'date'=>$date,'allocations'=>[['method'=>'UPI','amount'=>'200'],['method'=>'Cash','amount'=>'300']]];
$cleared=$ledger->clear($clear,$owner);
check($cleared['receipt_number']==='CR-000001','credit receipt numbering starts at one');
$after=$service->get((int)$credit['id']);
check($cleared['balance']==='500.00' && $after['amount_due']==='500.00' && $after['amount_paid']==='680.00' && $after['initial_amount_paid']==='180.00','clearance updates paid/due without rewriting original payment');
$receipt=$ledger->receipt($cleared['id']);
$receiptHtml=(new PDFService())->receiptHtml($receipt);
file_put_contents(ROOT.'/tmp/v2-receipt.pdf',(new PDFService())->render($receiptHtml));
DB::run("UPDATE credit_accounts SET customer_name='Changed name' WHERE id=?",[$account['id']]);
DB::run("UPDATE business_profile SET name='Changed business' WHERE id=1");
check((new PDFService())->receiptHtml($ledger->receipt($cleared['id']))===$receiptHtml,'receipt business and customer snapshots remain stable');
DB::run("UPDATE business_profile SET name='Ledger Test Business' WHERE id=1");
rejects(fn()=>$service->save($after,$owner,(int)$after['id']),'settled credit history protected from edits');
rejects(fn()=>$service->cancel((int)$after['id'],['version'=>$after['version'],'reason'=>'test'],$owner),'settled credit history protected from cancellation');
$bad=$clear; $bad['allocations']=[['method'=>'Cash','amount'=>'501']];
rejects(fn()=>$ledger->clear($bad,$owner),'overclear rejected');
$bad=$clear; $bad['date']=date('Y-m-d',strtotime($date.' -1 day'));
rejects(fn()=>$ledger->clear($bad,$owner),'backdated clearance rejected');
$ledger->clear($clear,$owner);
$after=$service->get((int)$credit['id']);
check($after['amount_due']==='0.00' && $after['amount_paid']==='1180.00' && $after['payment_status']==='Credit Cleared','full clearance updates invoice status');
check(count($ledger->get((int)$account['id'])['transactions'])===3,'history contains original credit and separate clearances');
check($report->dashboard($range)['outstanding_credit']==='0.00' && $report->dashboard($range)['credit_sales']==='0.00','dashboard credit metrics update after clearance');
rejects(fn()=>Auth::require($staff,'clear_credit'),'staff clearance permission denied');
rejects(fn()=>Auth::require($owner,'delete_transaction_data'),'owner destructive admin permission denied');
$returned=(new App\CreditNoteService())->create(['invoice_id'=>$inter['id'],'note_date'=>$date,'reason'=>'Return goods','settlement'=>'Refund','items'=>[['invoice_item_id'=>$inter['items'][0]['id'],'quantity'=>'1']]],$owner);
check($returned['totals']['total']==='1062.00' && $returned['totals']['gst']==='162.00','goods return excludes shipping and shipping GST');
$note=(new App\CreditNoteService())->get($returned['id']);
file_put_contents(ROOT.'/tmp/v2-credit-note.pdf',(new PDFService())->render((new PDFService())->creditNoteHtml($note)));
check(DocumentData::financialYear('2027-03-31')==='2026-27' && DocumentData::financialYear('2027-04-01')==='2027-28','financial year follows document date');
// Patch is repeatable and preserves existing records/settings.
$before=DB::one('SELECT COUNT(*) n,SUM(grand_total) total FROM invoices');
for($run=0;$run<2;$run++) foreach(explode(';',file_get_contents(ROOT.'/database/migrate-v2.1.sql')) as $sql) if(trim($sql)!=='') DB::connection()->exec($sql);
check($before===DB::one('SELECT COUNT(*) n,SUM(grand_total) total FROM invoices') && SettingsService::settings()['shipping_gst_rate']==='5.00','v2.1 migration repeatable without resetting invoices or settings');
$due['payment_allocations']=[];
$due['customer_mobile']='9000000033';
$pureCredit=$service->save($due,$owner);
$duplicated=$service->duplicate((int)$pureCredit['id'],$owner);
check($duplicated['amount_paid']==='0.00' && $duplicated['payment_status']==='Due','duplicating unpaid credit does not invent payment');
$export=(new App\ExportService())->start($range+['kind'=>'csv'],$admin);
App\AuditLogService::record($admin,'Bulk Transaction Deletion',null,['test_generation'=>true]);
rejects(fn()=>(new App\ExportService())->job($export['id'],$admin),'transaction deletion invalidates existing export snapshots');
$path=DB::transaction(fn()=>(new App\BackupService())->create());
check(is_file($path),'pre-deletion backup works inside the serialized transaction');
echo "\n$count total regression and v2 checks passed.\n";
