SET NAMES utf8mb4;
CREATE TABLE roles (id VARCHAR(10) PRIMARY KEY) ENGINE=InnoDB;
CREATE TABLE permissions (id VARCHAR(50) PRIMARY KEY, admin_only BOOLEAN NOT NULL DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id VARCHAR(10) NOT NULL, permission_id VARCHAR(50) NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(permission_id) REFERENCES permissions(id)) ENGINE=InnoDB;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, firebase_uid VARCHAR(128) UNIQUE, email VARCHAR(190) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, contact VARCHAR(30) NOT NULL DEFAULT '', role_id VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id)) ENGINE=InnoDB;
CREATE TABLE user_permissions (user_id BIGINT UNSIGNED NOT NULL, permission_id VARCHAR(50) NOT NULL, allowed BOOLEAN NOT NULL, PRIMARY KEY(user_id,permission_id), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(permission_id) REFERENCES permissions(id)) ENGINE=InnoDB;
CREATE TABLE business_profile (id INT PRIMARY KEY, name VARCHAR(160) NOT NULL DEFAULT '', address TEXT, gstin VARCHAR(15) NOT NULL DEFAULT '', email VARCHAR(190) NOT NULL DEFAULT '', state VARCHAR(2) NOT NULL DEFAULT '29', account_holder VARCHAR(160) NOT NULL DEFAULT '', bank_name VARCHAR(160) NOT NULL DEFAULT '', account_name VARCHAR(160) NOT NULL DEFAULT '', account_number VARCHAR(40) NOT NULL DEFAULT '', ifsc VARCHAR(11) NOT NULL DEFAULT '', branch VARCHAR(160) NOT NULL DEFAULT '', declaration TEXT, financial_year VARCHAR(7) NOT NULL DEFAULT '', logo VARCHAR(80) NOT NULL DEFAULT '', signature VARCHAR(80) NOT NULL DEFAULT '', updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE invoice_number_settings (id INT PRIMARY KEY, prefix VARCHAR(20) NOT NULL DEFAULT 'INV-', next_number BIGINT UNSIGNED NOT NULL DEFAULT 1, padding TINYINT UNSIGNED NOT NULL DEFAULT 5, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE system_settings (id INT PRIMARY KEY, settings JSON NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE invoices (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_number VARCHAR(50) NOT NULL UNIQUE, invoice_date DATE NOT NULL,
 customer_name VARCHAR(160) NOT NULL DEFAULT '', customer_mobile VARCHAR(30) NOT NULL DEFAULT '', customer_gstin VARCHAR(15) NOT NULL DEFAULT '', customer_email VARCHAR(190) NOT NULL DEFAULT '',
 billing_address TEXT, shipping_address TEXT, shipping_name VARCHAR(160) NOT NULL DEFAULT '', shipping_mobile VARCHAR(30) NOT NULL DEFAULT '', shipping_email VARCHAR(190) NOT NULL DEFAULT '', shipping_state VARCHAR(2) NOT NULL DEFAULT '', customer_state VARCHAR(2) NOT NULL DEFAULT '', customer_type ENUM('Registered','Unregistered') NOT NULL DEFAULT 'Unregistered', place_of_supply VARCHAR(2) NOT NULL,
 delivery_note VARCHAR(160) NOT NULL DEFAULT '', payment_terms VARCHAR(160) NOT NULL DEFAULT '', buyer_order_number VARCHAR(160) NOT NULL DEFAULT '', buyer_order_date DATE NULL, dispatch_doc_number VARCHAR(160) NOT NULL DEFAULT '', delivery_note_date DATE NULL, dispatch_through VARCHAR(160) NOT NULL DEFAULT '', destination VARCHAR(160) NOT NULL DEFAULT '', terms_of_delivery VARCHAR(500) NOT NULL DEFAULT '',
 payment_method ENUM('Cash','UPI','Card','Bank Transfer','Credit','Other') NOT NULL, payment_reference VARCHAR(100) NOT NULL DEFAULT '', notes TEXT,
 transporter VARCHAR(160) NOT NULL DEFAULT '', vehicle_number VARCHAR(30) NOT NULL DEFAULT '', business_snapshot JSON NOT NULL,
 subtotal DECIMAL(18,2) NOT NULL, discount DECIMAL(18,2) NOT NULL, shipping_charges DECIMAL(18,2) NOT NULL DEFAULT 0, shipping_gst_rate DECIMAL(5,2) NOT NULL DEFAULT 0, shipping_gst DECIMAL(18,2) NOT NULL DEFAULT 0, taxable DECIMAL(18,2) NOT NULL, cgst DECIMAL(18,2) NOT NULL, sgst DECIMAL(18,2) NOT NULL, igst DECIMAL(18,2) NOT NULL, gst DECIMAL(18,2) NOT NULL, round_off DECIMAL(18,2) NOT NULL, grand_total DECIMAL(18,2) NOT NULL,
 amount_paid DECIMAL(18,2) NOT NULL DEFAULT 0, amount_due DECIMAL(18,2) NOT NULL DEFAULT 0, payment_status ENUM('Paid','Partially Paid','Due','Credit Cleared','Cancelled') NOT NULL DEFAULT 'Paid', credit_bill BOOLEAN NOT NULL DEFAULT 0,
 status ENUM('Active','Cancelled') NOT NULL DEFAULT 'Active', cancellation_reason VARCHAR(500), version INT NOT NULL DEFAULT 1, duplicated_from BIGINT UNSIGNED NULL,
 created_by BIGINT UNSIGNED NOT NULL, updated_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id), FOREIGN KEY(updated_by) REFERENCES users(id), FOREIGN KEY(duplicated_from) REFERENCES invoices(id),
 INDEX idx_date(invoice_date,id), INDEX idx_customer(customer_name), INDEX idx_mobile(customer_mobile), INDEX idx_gstin(customer_gstin), INDEX idx_payment(payment_method,invoice_date), INDEX idx_status(status,invoice_date), INDEX idx_creator(created_by,invoice_date), CHECK(grand_total>=0)
) ENGINE=InnoDB;
CREATE TABLE invoice_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, position INT NOT NULL,
 product_name VARCHAR(160) NOT NULL, hsn_sac VARCHAR(12) NOT NULL DEFAULT '', description VARCHAR(500) NOT NULL DEFAULT '', unit VARCHAR(20) NOT NULL DEFAULT '', quantity DECIMAL(12,3) NOT NULL, rate DECIMAL(14,2) NOT NULL, discount_mode ENUM('Flat','Percent') NOT NULL DEFAULT 'Flat', discount_value DECIMAL(18,2) NOT NULL DEFAULT 0, discount DECIMAL(18,2) NOT NULL, gst_rate DECIMAL(5,2) NOT NULL,
 gross DECIMAL(18,2) NOT NULL, taxable DECIMAL(18,2) NOT NULL, cgst DECIMAL(18,2) NOT NULL, sgst DECIMAL(18,2) NOT NULL, igst DECIMAL(18,2) NOT NULL, gst DECIMAL(18,2) NOT NULL, total DECIMAL(18,2) NOT NULL,
 FOREIGN KEY(invoice_id) REFERENCES invoices(id), UNIQUE(invoice_id,position), INDEX idx_hsn(hsn_sac), CHECK(quantity>0), CHECK(taxable>=0)
) ENGINE=InnoDB;
CREATE TABLE payment_allocations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, position INT NOT NULL, method VARCHAR(40) NOT NULL, amount DECIMAL(18,2) NOT NULL, reference VARCHAR(100) NOT NULL DEFAULT '', created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE CASCADE, FOREIGN KEY(created_by) REFERENCES users(id), UNIQUE(invoice_id,position), CHECK(amount>0)) ENGINE=InnoDB;
CREATE TABLE credit_accounts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, customer_name VARCHAR(160) NOT NULL, customer_mobile VARCHAR(30) NOT NULL UNIQUE, customer_address TEXT NOT NULL, total_credit DECIMAL(18,2) NOT NULL DEFAULT 0, total_cleared DECIMAL(18,2) NOT NULL DEFAULT 0, balance DECIMAL(18,2) NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_credit_name(customer_name), CHECK(balance>=0)) ENGINE=InnoDB;
CREATE TABLE credit_transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, credit_account_id BIGINT UNSIGNED NOT NULL, invoice_id BIGINT UNSIGNED NULL, kind ENUM('Credit','Clearance','Cancellation') NOT NULL, receipt_number VARCHAR(50) NULL UNIQUE, receipt_snapshot JSON NULL, transaction_date DATE NOT NULL, amount DECIMAL(18,2) NOT NULL, balance_after DECIMAL(18,2) NOT NULL, created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(credit_account_id) REFERENCES credit_accounts(id) ON DELETE CASCADE, FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id), INDEX idx_credit_tx(credit_account_id,transaction_date,id), CHECK(amount>=0), CHECK(balance_after>=0)) ENGINE=InnoDB;
CREATE TABLE credit_transaction_allocations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, credit_transaction_id BIGINT UNSIGNED NOT NULL, position INT NOT NULL, method VARCHAR(40) NOT NULL, amount DECIMAL(18,2) NOT NULL, reference VARCHAR(100) NOT NULL DEFAULT '', FOREIGN KEY(credit_transaction_id) REFERENCES credit_transactions(id) ON DELETE CASCADE, UNIQUE(credit_transaction_id,position), CHECK(amount>0)) ENGINE=InnoDB;
CREATE TABLE activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, user_name VARCHAR(160) NOT NULL, invoice_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL, details JSON NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(invoice_id) REFERENCES invoices(id), INDEX idx_activity_date(created_at), INDEX idx_activity_invoice(invoice_id,id)) ENGINE=InnoDB;
CREATE TABLE invoice_edit_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, previous_values JSON NOT NULL, new_values JSON NOT NULL, changed_fields JSON NOT NULL, final_amount DECIMAL(18,2) NOT NULL, final_gst DECIMAL(18,2) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(invoice_id) REFERENCES invoices(id), FOREIGN KEY(user_id) REFERENCES users(id), INDEX(invoice_id,id)) ENGINE=InnoDB;
CREATE TABLE credit_notes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, note_date DATE NOT NULL, reason VARCHAR(500) NOT NULL, settlement ENUM('Refund','Adjustment') NOT NULL, reference VARCHAR(100) NOT NULL DEFAULT '', taxable DECIMAL(18,2) NOT NULL, cgst DECIMAL(18,2) NOT NULL, sgst DECIMAL(18,2) NOT NULL, igst DECIMAL(18,2) NOT NULL, gst DECIMAL(18,2) NOT NULL, round_off DECIMAL(18,2) NOT NULL DEFAULT 0, total DECIMAL(18,2) NOT NULL, created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(invoice_id) REFERENCES invoices(id), FOREIGN KEY(created_by) REFERENCES users(id), INDEX(note_date,id)) ENGINE=InnoDB;
CREATE TABLE sales_returns (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, credit_note_id BIGINT UNSIGNED NOT NULL, invoice_item_id BIGINT UNSIGNED NOT NULL, quantity DECIMAL(12,3) NOT NULL, taxable DECIMAL(18,2) NOT NULL, cgst DECIMAL(18,2) NOT NULL, sgst DECIMAL(18,2) NOT NULL, igst DECIMAL(18,2) NOT NULL, gst DECIMAL(18,2) NOT NULL, total DECIMAL(18,2) NOT NULL, FOREIGN KEY(credit_note_id) REFERENCES credit_notes(id), FOREIGN KEY(invoice_item_id) REFERENCES invoice_items(id), CHECK(quantity>0)) ENGINE=InnoDB;
CREATE TABLE integration_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, kind VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, response JSON, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(invoice_id) REFERENCES invoices(id)) ENGINE=InnoDB;
CREATE TABLE rate_limits (bucket VARCHAR(64) PRIMARY KEY, hits INT NOT NULL, expires_at BIGINT NOT NULL, INDEX(expires_at)) ENGINE=InnoDB;
